version: '2.4'
services:
  backend:
    build:
      context: .
      dockerfile: ./devops/docker/backend/Dockerfile
    image: backend:latest
    command: bash -c "gunicorn config.wsgi:application --workers 1 --bind 0.0.0.0:8000 --timeout 0 --log-level debug"
    env_file:
      - envs/.env
    restart: "on-failure"
    ports:
      - 80:8000